title: Dr. Víctor Osores
description: Facultad de Ciencias Básicas, Dpto. Matemática, Física y Estadística, Universidad Católica del Maule.
github.repository_name: https://github.com/victorosores
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
